import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Badge } from "~/components/ui/badge";
import { buttonVariants } from "~/components/ui/button";
import { cn } from "~/lib/utils";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Paperflow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div className="container mx-auto flex flex-row items-center px-4 py-4">
          <Link
            href="/"
            className="flex flex-row items-center text-2xl font-semibold text-primary"
          >
            <Image
              width="80"
              height="80"
              src="/branding.png"
              alt="app branding illustration"
            />
            <span>Paperflow</span>
          </Link>
        </div>
      </nav>
      <header className="flex min-h-screen flex-col items-center justify-start bg-background text-center">
        <Badge variant="outline" className="mb-4">
          Introducing Paperflow Alpha 0.1
        </Badge>
        <h1 className="inline-block scroll-m-20 bg-gradient-to-r from-primary to-primary/80 bg-clip-text text-4xl font-semibold tracking-tight text-transparent lg:text-6xl">
          Paperflow is a better way to <br /> get rid of your paperwork
        </h1>
        <p className="max-w-2xl text-2xl leading-7 text-primary/80 [&:not(:first-child)]:mt-6">
          Meet the new standard for modern digitized paper. Build forms,
          triggers, pdfs, emails and create new workflows.
        </p>
        <Link
          className={cn(
            buttonVariants({ variant: "default", size: "lg" }),
            "mt-10"
          )}
          href={sessionData ? "/dashboard" : "/login"}
        >
          Get Started
        </Link>
        {/* <Button
          onClick={sessionData ? () => void signOut() : () => void signIn()}
        >
          {sessionData ? "Sign out" : "Sign in"}
        </Button> */}
      </header>
    </>
  );
};

export default Home;
